site_name: Hospital Documentation

nav:
  - Home: index.md
  - Tablas de Synthea: tables.md
  - Arquitectura en AWS: architecture.md
  - Glosario: glossary.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
theme:
  name: material
  features:
    - tags
    - search.highlight
    - search.suggest
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode



